apiVersion: v1
kind: Pod
metadata:
  name: cpu-restore
  namespace: kybernate-system
spec:
  runtimeClassName: kybernate
  containers:
  - name: counter
    image: python:3.9-slim
    command: ["sleep", "infinity"]
    env:
    - name: RESTORE_FROM
      value: "/tmp/kybernate-checkpoint"
